spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url:
    username: salt
    password: saltstack
    driverClassName: com.mysql.jdbc.Driver
  pagehelper.helperDialect: mysql
  pagehelper.reasonable: true