spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysql.dev:3358/admin
    username: salt
    password: saltstack
    driverClassName: com.mysql.jdbc.Driver
pagehelper:
  reasonable: true